version: 1.0.{build}
environment:
  matrix:
    - LINKAGE: shared
      RUNTIME_LIBRARY: MD
      TOOLSET: v120
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - LINKAGE: static
      RUNTIME_LIBRARY: MD
      TOOLSET: v120
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - LINKAGE: shared
      RUNTIME_LIBRARY: MT
      TOOLSET: v120
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - LINKAGE: static
      RUNTIME_LIBRARY: MT
      TOOLSET: v120
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013

    - LINKAGE: shared
      RUNTIME_LIBRARY: MD
      TOOLSET: v140
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - LINKAGE: static
      RUNTIME_LIBRARY: MD
      TOOLSET: v140
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - LINKAGE: shared
      RUNTIME_LIBRARY: MT
      TOOLSET: v140
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - LINKAGE: static
      RUNTIME_LIBRARY: MT
      TOOLSET: v140
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - LINKAGE: shared
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - LINKAGE: static
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - LINKAGE: shared
      RUNTIME_LIBRARY: MT
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - LINKAGE: static
      RUNTIME_LIBRARY: MT
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
matrix:
  fast_finish: true
platform:
  - x86
  - x64
configuration: Release
install: install.bat
build_script: build.bat
test: off
artifacts:
  - path: '*.zip'
deploy:
  description: 'Header, library, and executable for x264.'
  provider: GitHub
  auth_token:
    secure: QSdxjkooPHApqh95gD9duaZBxmv/5zWzDcukjNQGmbedwEu0BvzgA6HUEXpvni25
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
cache:
  - c:\nasm-2.13.03-win64.zip
